### ISSUE TITLE
Not working for mp3 audio file

### ISSUE THREAD

**Issue by ervinod** [Eittipat/audio_visualizer#1]
While playing mp3 audio file, visualizer is showing but there is noise while playing audio. can u pls check and resolve this issue.

**Comment by Eittipat** [comment]
Thank you for using this library.

Because this library is using raw_sound (https://pub.dev/packages/raw_sound) which support only pcm file.
If you wish to play mp3, you should convert them into pcm format.

Frankly speak, I'm using raw_sound because it provides audio raw buffer while playing audio. So I can read it and display visualizer. Implementing full-features media player is hard. And there is no other plugins that provides raw audio buffer at this time. 

However, you still have hope. https://pub.dev/packages/just_audio is implementing their visualizer feature.

**Comment by Eittipat** [comment]
I've updated my package, let's try
